### ISSUE TITLE
Great functions hidden in scroll area below running text

### ISSUE THREAD

**Issue by westnordost** [breunigs/veloroute#12]
This is an awesome map. Also, really great that there is quite street imagery for all the routes! The depth of the information available there is stunning! Much thanks for that! Definitely a lot to browse there!

All the more it is a pity that many great features and information are a bit hidden in that box on the upper right corner. The box in the upper right corner looks more as if it should only contain the legend and some explanatory text.
One great feature is the meta information for each route, most of all the "[Wegqualität bewerten](https://veloroute.hamburg/quality)", which opens up a completely new view. I missed this feature at first. 

I have a few suggestions regarding this:
- Perhaps, there could be a large button on the map view instead of a link text in the box to switch to the quality view and back - just like there is a button on Google Maps to switch between Satellite and Map view
- Shorten the text about download, show the download hints and hints for eligible applications in a popup that is displayed when clicking the download?
- Certain content currently solved as running text in the box could be replaced by interaction on the map or shorter links. For example, one can already simply click on the routes to get details about it instead of clicking on the buttons for the routes in the box

**Comment by breunigs** [comment]
I'm glad you like it and appreciate your feedback. I'm aware the navigation is not that great and the site would benefit from a central navigation to allow easier access to the content. There's more hidden features that I'm not sure how to integrate (e.g. https://veloroute.hamburg/bau which is the bubbles you see in quality view, ordered by planned start date).

Ideally the quality view can be rolled into the regular interface upon zooming in some such. For instance, https://fahrrad.hamburg/de/service/velorouten/ uses dashed lines to denote "redesign/reconstruction still pending". At the same time I also want to simplify the grading to be simpler and more apparent when cycling there. I'm thinking along the lines "can I have a conversation easily?" (width, separation from cars) and "achievable speed" (surface quality and routing) and then do manual grading, maybe light crowd sourcing.

Showing the Download Tools/Hints in a Popup is a great idea. It's on the todo, but it'll be a while before I get to it.

I'm not quite sure I understand your last bullet point fully. I guess part of it is answered by the central navigation (for which I have no good concept yet) and the "rolled in quality view". Can you elaborate which content you refer to?

Additionally, can you please state which type of device you're using? I'm mostly curious about screen size, because it has the most impact on how the site can be used. Fitting it onto tablets was still doable, but cellphones were a challenge.

**Comment by westnordost** [comment]
> Can you elaborate which content you refer to?

I mean: Navigation that is already accessible from interaction on the map doesn't need to be in the box:
![image](https://user-images.githubusercontent.com/4661658/64493308-d1423480-d27e-11e9-8f63-67e6e8652c39.png)

> Additionally, can you please state which type of device you're using?

Got a PC screen with 2560x1440 resolution, but I seldomly have the browser on full screen.

---

Regarding the navigation for the construction sites: Well, what about three big buttons (Preview Image + Title) on one corner of on the map view:
- Routen
- Qualität
- Baustellen
Each of these links switches to one of the views above.

**Comment by breunigs** [comment]
I've updated the site recently and both the quality view and the articles are shown in the map upon zooming in. This should make them more discoverable.

The color scheme for quality view is intentionally less intensive. The main reason is that people have different needs and therefore arrive at different conclusions and I did not feel the discussion "still green or already yellow?" to be very fruitful. I'm hoping that the opacity change still conveys "there's improvements desired here" without getting into the specifics. Of course, I still want to improve the rating/quality view as a hole to incorporate the subjective feel of a segment. On the more technical side, switching the color schemes on zoom makes for a surprising and jarring effect. Plus, opacity is automatically color vision impairment friendly, so yay for that.

I still need to get to the other points you brought up.

**Comment by breunigs** [comment]
The site has a new layout which gives more space to the text. Most of your remarks were about variants to increase the "above the fold"  visibility of the articles, which I think is addressed now. Well, on mobile people needs to swipe left once to view the text section, but I guess I can change the text to be visible by default and have it auto collapse when showin something on the map/images.

On a side note, I mostly removed the GPX download feature because it was seldomly used. The city itself provides up to date GPX nowadays, too, and for everyone else automatically providing these links in a routing tool like Komoot or Google Maps seems the better choice.

Please re-open if you think your original issue has not been addressed, or create new issues as needed. Cheers.
